name: 'Cloudflare Workers PR Preview'
description: 'Automatically deploy PR previews to Cloudflare Workers (like Cloudflare Pages does for static sites)'
author: 'mertselimb'

branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  cloudflare-api-token:
    description: 'Cloudflare API Token with Workers permissions'
    required: true
  cloudflare-account-id:
    description: 'Cloudflare Account ID'
    required: true
  build-command:
    description: 'Command to build your project (e.g., "npm run build")'
    required: false
    default: 'npm run build'
  install-command:
    description: 'Command to install dependencies (e.g., "npm install", "pnpm install")'
    required: false
    default: 'npm install'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  working-directory:
    description: 'Working directory for the project'
    required: false
    default: '.'
  subdomain:
    description: 'Custom subdomain prefix (defaults to repository name)'
    required: false
    default: ''
  comment-on-pr:
    description: 'Whether to comment the preview URL on the PR'
    required: false
    default: 'true'
  wrangler-version:
    description: 'Wrangler version to use (defaults to latest)'
    required: false
    default: ''
  package-manager:
    description: 'Package manager to use (npm, pnpm, yarn)'
    required: false
    default: 'npm'

outputs:
  preview-url:
    description: 'The deployed preview URL'
    value: ${{ steps.deploy.outputs.preview-url }}
  deployment-id:
    description: 'The deployment ID'
    value: ${{ steps.deploy.outputs.deployment-id }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}
        cache-dependency-path: ${{ inputs.working-directory }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.install-command }}

    - name: Build project
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.build-command }}

    - name: Determine subdomain
      id: subdomain
      shell: bash
      run: |
        if [ -n "${{ inputs.subdomain }}" ]; then
          echo "value=${{ inputs.subdomain }}" >> $GITHUB_OUTPUT
        else
          # Use repository name as subdomain
          REPO_NAME="${{ github.event.repository.name }}"
          echo "value=${REPO_NAME}" >> $GITHUB_OUTPUT
        fi

    - name: Deploy to Cloudflare Workers
      id: deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.cloudflare-api-token }}
        accountId: ${{ inputs.cloudflare-account-id }}
        command: deploy --name ${{ steps.subdomain.outputs.value }}-pr-${{ github.event.pull_request.number }}
        workingDirectory: ${{ inputs.working-directory }}
        wranglerVersion: ${{ inputs.wrangler-version }}

    - name: Set preview URL
      id: url
      shell: bash
      run: |
        SUBDOMAIN="${{ steps.subdomain.outputs.value }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"
        # Extract username/account from repository owner
        OWNER="${{ github.repository_owner }}"
        PREVIEW_URL="https://${SUBDOMAIN}-pr-${PR_NUMBER}.${OWNER}.workers.dev"
        echo "preview-url=${PREVIEW_URL}" >> $GITHUB_OUTPUT
        echo "Preview URL: ${PREVIEW_URL}"

    - name: Comment on PR
      if: inputs.comment-on-pr == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          const previewUrl = '${{ steps.url.outputs.preview-url }}';

          const comment = `## 🚀 Preview Deployed!

          ✨ **Preview URL:** ${previewUrl}

          ---
          <sub>Deployed with [Cloudflare Workers PR Preview](https://github.com/${{ github.repository }})</sub>`;

          // Check if we already commented
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
          });

          const botComment = comments.find(comment =>
            comment.user.type === 'Bot' &&
            comment.body.includes('🚀 Preview Deployed!')
          );

          if (botComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: comment
            });
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
          }
